# Generated by Django 4.0 on 2021-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('balloon_id', models.AutoField(primary_key=True, serialize=False)),
                ('balloon_n_number', models.CharField(max_length=16)),
                ('balloon_make', models.CharField(max_length=50)),
                ('balloon_size', models.CharField(max_length=50)),
                ('balloon_model', models.CharField(max_length=50)),
                ('balloon_name', models.CharField(max_length=50)),
            ],
        ),
    ]
