# Generated by Django 4.0 on 2021-12-17 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_profile', '0002_balloon_balloon_airworthiness_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='balloon_airworthiness_date',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='balloon_registration_expiration',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
    ]
