# Generated by Django 4.0 on 2021-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_certificateinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
