# Generated by Django 4.0 on 2021-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_statelookup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateLookUp',
        ),
    ]
