# Generated by Django 4.0 on 2021-12-23 19:43

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_delete_statelookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotinformation',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pilotinformation',
            name='zip',
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
    ]
