# Generated by Django 4.0 on 2021-12-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft_profile', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAreaOfOperation',
            fields=[
                ('paoo_id', models.AutoField(primary_key=True, serialize=False)),
                ('paoo_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLessonPlan',
            fields=[
                ('plp_id', models.AutoField(primary_key=True, serialize=False)),
                ('plp_date', models.DateField(auto_now_add=True)),
                ('plp_objective', models.TextField(max_length=1024)),
                ('plp_instructor_action', models.TextField(max_length=1024)),
                ('plp_student_action', models.TextField(max_length=1024)),
                ('plp_completion_standards', models.TextField(max_length=1024)),
                ('plp_flight_time', models.CharField(max_length=16)),
                ('plp_notes', models.TextField(max_length=2048)),
                ('plp_balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft_profile.balloon')),
                ('plp_instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='user_profile.pilotinformation')),
                ('plp_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user_profile.pilotinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateStandards',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('ps_name', models.CharField(max_length=254)),
                ('ps_aoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.privateareaofoperation')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLessonPlanElements',
            fields=[
                ('plpe_id', models.AutoField(primary_key=True, serialize=False)),
                ('plpe_student_action_no_assistance', models.BooleanField(default=False)),
                ('plpe_student_action_some_assistance', models.BooleanField(default=False)),
                ('plpe_student_action_needed_assistace', models.BooleanField(default=False)),
                ('plpe_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.privatestandards')),
                ('plpe_private_lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.privatelessonplan')),
            ],
        ),
    ]
